name: Cache Test Workflow

on:
  push:   # runs whenever you push code
    branches: [ main ]   # change to "master" if your repo default branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Cache dependencies
      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-7799caf

      # Prime the cache step
      - name: prime-cache-7799caf
        run: echo "Cache result: ${{ steps.cache-step.outputs.cache-hit }}"
